### ISSUE TITLE
Insight on Things pushes AWS IoT Policy with "undefined" as ARN Account ID

### ISSUE THREAD

**Issue by MattStarfield** [MicrochipTech/aws-iot-insight-on-things-desktop-app#10]
I'm using the [AWS IoT Ethernet Kit (DM990004](https://github.com/MicrochipTech/aws-iot-firmware-pic32mz/blob/master/documents/iot-ethernet-out-of-box-guide.md). Everytime I tried to go through a board setup process, the board was not successfully connecting to AWS.

After troubleshooting and inspection, I found that the Insight on Things app's commissioning process has been uploading the Thing Policy with "undefined" as the ARN Account ID number (see example below). If I edit the Policy and create a new version that replaces "undefined" with my ARN Account ID, the board successfully connects.

I tried to uninstall Insight on Things and deleted the folder in user/AppData/Roaming/Insight on Things, the reinstalled Insight on Things hoping it would reset whatever field is causing this issue, but the issue persists.

This looks like a [similar issue here](https://github.com/MicrochipTech/aws-iot-insight-on-things-desktop-app/issues/2), which was supposed to be addressed in v2.0.0

Additionally, I can manipulate the device shadow on AWS IoT directly, but the shadow in Insight on Things doesn't work. Insight on Things doesn't even show my board in the Thing Home list.

{

  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:us-east-1:undefined:client/5410ec04db8e"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish"
      ],
      "Resource": [
        "arn:aws:iot:us-east-1:undefined:topic/$aws/things/5410ec04db8e/shadow/update",
        "arn:aws:iot:us-east-1:undefined:topic/$aws/things/5410ec04db8e/shadow/get"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "arn:aws:iot:us-east-1:undefined:topicfilter/$aws/things/5410ec04db8e/shadow/update/delta",
        "arn:aws:iot:us-east-1:undefined:topicfilter/$aws/things/5410ec04db8e/shadow/update/accepted",
        "arn:aws:iot:us-east-1:undefined:topicfilter/$aws/things/5410ec04db8e/shadow/update/rejected",
        "arn:aws:iot:us-east-1:undefined:topicfilter/$aws/things/5410ec04db8e/shadow/get/accepted",
        "arn:aws:iot:us-east-1:undefined:topicfilter/$aws/things/5410ec04db8e/shadow/get/rejected"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:us-east-1:undefined:topic/$aws/things/5410ec04db8e/shadow/update/delta",
        "arn:aws:iot:us-east-1:undefined:topic/$aws/things/5410ec04db8e/shadow/update/accepted",
        "arn:aws:iot:us-east-1:undefined:topic/$aws/things/5410ec04db8e/shadow/update/rejected",
        "arn:aws:iot:us-east-1:undefined:topic/$aws/things/5410ec04db8e/shadow/get/accepted",
        "arn:aws:iot:us-east-1:undefined:topic/$aws/things/5410ec04db8e/shadow/get/rejected"
      ]
    }
  ]
}

**Comment by MattStarfield** [comment]
I believe I've tracked this problem down to the iam.CreateUser function ([insight.js L#1151](https://github.com/MicrochipTech/aws-iot-insight-on-things-desktop-app/blob/c3df0aa5ff6f65946a3bc32e32fea0ac7528abc6/app/content/js/insight.js#L1150)).

I've deleted the Thing, Certificate, and Policy from my AWS-IoT account. I've uninstalled Insight on Things.exe from my PC, then deleted the folder at C:\Users\[username]\AppData\Roaming\Insight on Things and the .insight file at C:\Users\[username]

Then I install Insight on Things, and go through the initial setup for the board. I've turned on the DevTool console and get the following error on Setup, which is preventing _accountnumber_ from being set.

I cannot tell where that username is being retained for Insight on Things is looking to find the "pre-existing" user.

`Error: User with name 5410ec04db8e already exists.
    at Request.extractError (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\protocol\query.js:40:29)
    at Request.callListeners (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\request.js:668:14)
    at Request.fsm.setupStates.transition (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\request.js:670:12)
    at Request.callListeners (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\sequential_executor.js:115:18) "EntityAlreadyExists: User with name 5410ec04db8e already exists.
    at Request.extractError (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\protocol\query.js:40:29)
    at Request.callListeners (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\request.js:668:14)
    at Request.fsm.setupStates.transition (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\request.js:670:12)
    at Request.callListeners (C:\Users\mattg\AppData\Local\Programs\Insight\resources\app.asar\node_modules\aws-sdk\lib\sequential_executor.js:115:18)"`
